"""
Basic tests for PY-to-Franuc-TP library.
"""

import sys
import os
import unittest

# Add parent directory to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

from fanuc_tp import FanucTPWriter, Position
from fanuc_tp.commands import MovementCommand, LogicCommand, IOCommand


class TestPosition(unittest.TestCase):
    """Test Position class."""
    
    def test_cartesian_position(self):
        """Test cartesian position creation."""
        pos = Position.from_xyz(100, 200, 300, 0, 180, 0)
        self.assertEqual(pos.x, 100)
        self.assertEqual(pos.y, 200)
        self.assertEqual(pos.z, 300)
        self.assertEqual(pos.w, 0)
        self.assertEqual(pos.p, 180)
        self.assertEqual(pos.r, 0)
    
    def test_joint_position(self):
        """Test joint position creation."""
        pos = Position.from_joints(10, 20, 30, 40, 50, 60)
        self.assertEqual(len(pos.joints), 6)
        self.assertEqual(pos.joints[0], 10)
        self.assertEqual(pos.joints[5], 60)
    
    def test_cartesian_string_output(self):
        """Test cartesian position string output."""
        pos = Position.from_xyz(100, 200, 300)
        output = pos.to_cartesian_string(1)
        self.assertIn("P[1]", output)
        self.assertIn("100.000", output)
        self.assertIn("200.000", output)
        self.assertIn("300.000", output)
    
    def test_joint_string_output(self):
        """Test joint position string output."""
        pos = Position.from_joints(10, 20, 30, 40, 50, 60)
        output = pos.to_joint_string(1)
        self.assertIn("P[1]", output)
        self.assertIn("10.000", output)
        self.assertIn("60.000", output)


class TestCommands(unittest.TestCase):
    """Test command classes."""
    
    def test_movement_command(self):
        """Test movement command creation."""
        cmd = MovementCommand('J', 1, 50, 'FINE')
        output = cmd.to_tp_string()
        self.assertIn('J P[1] 50% FINE', output)
    
    def test_logic_command_if(self):
        """Test IF logic command."""
        cmd = LogicCommand('IF', 'DI[1]=ON')
        output = cmd.to_tp_string()
        self.assertEqual(output, 'IF DI[1]=ON THEN')
    
    def test_logic_command_else(self):
        """Test ELSE logic command."""
        cmd = LogicCommand('ELSE')
        output = cmd.to_tp_string()
        self.assertEqual(output, 'ELSE')
    
    def test_io_command_digital_output(self):
        """Test digital output command."""
        cmd = IOCommand('DO', 1, True)
        output = cmd.to_tp_string()
        self.assertEqual(output, 'DO[1]=ON ;')
    
    def test_io_command_digital_output_false(self):
        """Test digital output command false."""
        cmd = IOCommand('DO', 1, False)
        output = cmd.to_tp_string()
        self.assertEqual(output, 'DO[1]=OFF ;')


class TestFanucTPWriter(unittest.TestCase):
    """Test FanucTPWriter class."""
    
    def setUp(self):
        """Set up test fixtures."""
        self.tp = FanucTPWriter("TEST")
    
    def test_program_creation(self):
        """Test basic program creation."""
        self.assertEqual(self.tp.program_name, "TEST")
        self.assertEqual(len(self.tp.commands), 0)
    
    def test_add_comment(self):
        """Test adding comments."""
        self.tp.add_comment("Test comment")
        self.assertEqual(len(self.tp.commands), 1)
        output = self.tp.commands[0].to_tp_string()
        self.assertEqual(output, "! Test comment")
    
    def test_add_movement(self):
        """Test adding movement commands."""
        self.tp.move_joint(1, 50)
        self.assertEqual(len(self.tp.commands), 1)
        output = self.tp.commands[0].to_tp_string()
        self.assertIn("J P[1] 50% FINE", output)
    
    def test_add_position(self):
        """Test adding positions."""
        pos = Position.from_xyz(100, 200, 300)
        self.tp.add_position(1, pos)
        self.assertEqual(len(self.tp.positions), 1)
        self.assertIn(1, self.tp.positions)
    
    def test_method_chaining(self):
        """Test method chaining."""
        result = (self.tp.add_comment("Start")
                 .move_joint(1, 50)
                 .set_digital_output(1, True)
                 .add_comment("End"))
        
        self.assertEqual(result, self.tp)  # Should return self
        self.assertEqual(len(self.tp.commands), 4)
    
    def test_program_generation(self):
        """Test complete program generation."""
        pos = Position.from_xyz(100, 200, 300)
        self.tp.add_position(1, pos)
        self.tp.add_comment("Test program")
        self.tp.move_joint(1, 50)
        
        program = self.tp.generate_tp_program()
        
        # Check program structure
        self.assertIn("/PROG  TEST", program)
        self.assertIn("Generated by PY-to-Franuc-TP", program)
        self.assertIn("! Test program", program)
        self.assertIn("J P[1] 50% FINE", program)
        self.assertIn("P[1]", program)
        self.assertIn("100.000", program)
        self.assertIn("END ;", program)
        self.assertIn("/END", program)
    
    def test_clear_method(self):
        """Test clear method."""
        self.tp.add_comment("Test")
        self.tp.move_joint(1, 50)
        pos = Position.from_xyz(100, 200, 300)
        self.tp.add_position(1, pos)
        
        self.assertEqual(len(self.tp.commands), 2)
        self.assertEqual(len(self.tp.positions), 1)
        
        self.tp.clear()
        
        self.assertEqual(len(self.tp.commands), 0)
        self.assertEqual(len(self.tp.positions), 0)
        self.assertEqual(self.tp.current_line, 1)


if __name__ == '__main__':
    unittest.main()